### ISSUE TITLE
Compatibility packages 

### ISSUE THREAD

**Issue by hcarty** [ocamllibs/stdcompat#1]
Would it be open to using the bytes, result and seq compatibility packages to provide type compatibility with other libraries?

**Comment by thierry-martinez** [comment]
Sorry for the late answer and thank you for your pull request https://github.com/thierry-martinez/stdcompat/pull/2 . It is a great suggestion, but we will have to find a way to be compatible with these packages without adding mandatory external dependencies to stdcompat.

**Comment by thierry-martinez** [comment]
stdcompat is now compatible with result and seq compatibility packages (https://github.com/thierry-martinez/stdcompat/commit/92b7bc6d5bce9e7940b15638e71259776643eb8f). There is already type compatibility with the bytes compatibility package, since `Bytes.t` is an alias for `string`, at least when `Bytes` is not provided by the standard library itself. Do you think about something specific to do relatively to the bytes compatibility package?

**Comment by hcarty** [comment]
I think what you've done covers this - thank you very much!
