### ISSUE TITLE
compilation fails "missing autoreconf" and "no such file or directory"

### ISSUE THREAD

**Issue by hannesm** [ocamllibs/stdcompat#28]
Hey,

I tried to opam install stdcompat, but somehow it fails. The dependency to "autoreconf" is missing from the opam file.

Also, after installing autoconf 2.71, I end up with the following issue:
```
autoreconf2.71: running: aclocal --force 
Can't exec "aclocal": No such file or directory at /usr/local/share/autoconf2.71/Autom4te/FileUtils.pm line 274.
```

And I don't understand what I can do about it. Any ideas?

**Comment by hannesm** [comment]
I managed to remove "stdcompat" from my dependency cone. Closing.

**Comment by shindere** [comment]
Hello Hannes,

Very sorry this could not be addressed in due time.

Since version 19 of stdcompat autoconf is no longer a dependency as the
files it generates are now shipped with the release tarballs.

In addition, since release 21, the dune build invoked by Opam does not even
call configure, nor does it rely on ocamlfind any longer.

I am very sorry you had to stop using stdcompat and hope you will feel
encouraged to start using it again.

As mentionned elsewhere, the plan is to make sure a new release of stdcompat
is published simultaneously with the corresponding compiler version,
hopefully starting with OCaml 5.4.

**Comment by hannesm** [comment]
Dear Sébastien, thanks for your kind message. That sounds excellent for the future of stdcompat. :)

**Comment by shindere** [comment]
Many thanks for your kind and supportive response!
